### ISSUE TITLE
deployment issue on multiple devices

### ISSUE THREAD

**Issue by immartian** [blakev/python-syncthing#10]
I'm running this script on multiple devices, and I wish to expand more in the future. What's the best strategy to configure API_KEY to make sure it's not relying on manual inputs one by one?

**Comment by blakev** [comment]
I would use environment variables,

```python

import os
from syncthing import Syncthing

sync = Syncthing(api_key=os.getenv('SYNCTHING_API', None))
```

However, I'm open to suggestions since I need to upgrade this module for Syncthing v0.14.x and just haven't had the time lately.
