### ISSUE TITLE
No examples or API documentation provided

### ISSUE THREAD

**Issue by jerryjacobs** [blakev/python-syncthing#2]
As I want to integrate syncthing API reading into collectd for data monitoring I need to specify the host/port etcetera. In the master branch only a simple test is provided. 

Could you add some stand-alone examples of using the library?

**Comment by blakev** [comment]
Yeah, sorry I've been out of town -- I'll get right on that! Thanks for looking :)

**Comment by jerryjacobs** [comment]
Thanks!
